name: Release And Package

on: push

jobs:
  build-windows-installer:
    runs-on: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make staging directory
        run: mkdir staging

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Gluon Build and Package
        shell: cmd
        run: .\mvnw -B -Pdesktop gluonfx:build gluonfx:package
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Try running the built image
        shell: powershell
        continue-on-error: false
        run: |
          # Start the process in the background, redirecting stdout and stderr to a file
          $process = Start-Process -FilePath target/gluonfx/x86_64-windows/GluonDemo.exe -RedirectStandardOutput process_output.log -RedirectStandardError process_output_err.log -NoNewWindow -PassThru

          # Wait for a few seconds (adjust as needed)
          Start-Sleep -Seconds 10

          Write-Host "==== Printing process_output.log for debugging:"
          Get-Content -Path process_output.log

          Write-Host "==== Printing process_output_err.log for debugging:"
          Get-Content -Path process_output_err.log

          # Kill the process if it is still running
          if (Get-Process -Id $process.Id -ErrorAction SilentlyContinue) {
            Write-Host "==== Process is still running, terminating it."
            Stop-Process -Id $process.Id
          } else {
            Write-Host "==== Process has already exited, but it should have been running."
            Exit 1
          }

      - name: Copy native bundles to staging
        run: |
          cp -r target/gluonfx/x86_64-windows/*.exe staging
          cp -r target/gluonfx/x86_64-windows/*.msi staging

      - name: Upload target for debugging
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
